### ISSUE TITLE
Audio in majority of games is very low compared to other cores

### ISSUE THREAD

**Issue by Zophar1** [MiSTer-devel/MegaCD_MiSTer#106]
An odd issue I've noticed since I've been streaming Sega CD games on Twitch more often with the MiSTer. I'm noticing that game audio seems very low compared to most other MiSTer cores, to the point where games with voice dialogue can be near unplayable when using the MiSTer on a gaming monitor with built in speakers as I am (you can only amplify them to get so loud).

Can we possible look into this and potentially allow for an "audio boost" setting here? I don't remember an original Model 1 Sega CD sounding this low by default on actual hardware and a CRT tube, but it was a long time ago... thanks.

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/MegaCD_MiSTer/issues/88 - Duplicate issue.

**Comment by sorgelig** [comment]
With many audio sources each source become quieter. Probably can add a compressor

**Comment by Zophar1** [comment]
Hey - just wanted to add that the audio level is low on HDMI digital output compared to other cores on the same signal chain. Also, birdybro suggested a fix in issue #88 (similar options to the TGCD core?) - could this be a viable solution for Sega CD as well?

Also - after reading #88, I agree with birdybro's assessment that this is a duplicate and this issue could be closed, and further discussion continued on #88 if necessary.
