### ISSUE TITLE
Unable to boot any game after release 20230716

### ISSUE THREAD

**Issue by farsil** [MiSTer-devel/MegaCD_MiSTer#108]
It looks like the core isn't able to properly load the BIOS file. As a result of this, no games are booting for me.

During startup the core only displays the background image of the BIOS, but no animation or sound. When I manually reload the backup RAM, it displays the disc check message, and then it gets stuck on the loading screen forever. I can provide a capture of the behavior if useful.

As a workaround, I had to rollback to version 20230224, which works fine.

I am using the following folder structure and the BIOS files from the bios_db database.

![image](https://github.com/MiSTer-devel/MegaCD_MiSTer/assets/18445221/118425f7-21c6-4835-90d6-4e898c2a743b)

The SD Card I'm using is a Samsung Evo Plus 256GB.

**Comment by sorgelig** [comment]
Please use MiSTer forum https://misterfpga.org/ to discuss usage issues.
There is no problem to boot games, otherwise many users will complain. It's something with your specific setup.
Use github to reposrt the problem more specifically.

**Comment by farsil** [comment]
Hmm although it does work fine with an earlier version of the core, so I thought this was a regression. Will consult the people on the forum first, thanks.

**Comment by atma-stackoverflow** [comment]
I am seeing the same.  Roll back to an early 2022 version, no problem.  I've checked both this and the thread on misterfpga and seen no real resolution other than run a very old version.  CHD and cue/bin exhibit an identical issue.

Games play off the SD fine on desktop or old version of core.  It's verifiably not a counterfeit.

All other cores have worked flawlessly.  It may not be a universal problem but it does exist with the exact symptoms described here on my hardware.  Bought prebuilt from a reputable vendor, misteraddons.com.

Pretty sure the SDRAM isn't the problem either, N64 works as does an earlier version of the MegaCD core.

I would love to help track this down but I must admit I'm clueless where to start.

**Comment by farsil** [comment]
After release 20240408 I am happy to say that I don't get this issue anymore. Closing this!
