### ISSUE TITLE
Pier Solar

### ISSUE THREAD

**Issue by Indcsion** [MiSTer-devel/MegaCD_MiSTer#12]
Is there anyway to use the enhanced audio cd for pier solar? I think it uses the genesis rom with the cd. Rysha might already know how to fix it but I figured Id ask on here as well.

**Comment by SegaSnatcher** [comment]
> Is there anyway to use the enhanced audio cd for pier solar? I think it uses the genesis rom with the cd. Rysha might already know how to fix it but I figured Id ask on here as well.

IMHO, its best to use forums or Discord for general questions like this.  

Anyways, I'm sure if its not already implemented it will be eventually.  Still early days mind you.

**Comment by Indcsion** [comment]
I just didnt know if it was an issue with how the core works or Im doing it wrong.

**Comment by Kitrinx** [comment]
This would require the genesis core and the Mega CD core to be merged, which does not currently appear to be technically feasible.

**Comment by sorgelig** [comment]
implemented
