### ISSUE TITLE
Newest release causes screen to go crazy. 

### ISSUE THREAD

**Issue by Techsteps** [MiSTer-devel/MegaCD_MiSTer#15]
Just tried the latest release and the screen resolution goes crazy. Horizontal roll and flashing static.

**Comment by dpowers86** [comment]
Got the same thing once on this version of the MegaCD core. Had it hapen on other cores too. A cold reboot seems to always fix it.

**Comment by sorgelig** [comment]
Power cycle or hard reset fixes it. It's not related to specific core and happens time after time in any core.

**Comment by Techsteps** [comment]
Thank you guys. I will close this then .
