### ISSUE TITLE
Non working using 64MB SDRAM

### ISSUE THREAD

**Issue by Aquas77** [MiSTer-devel/MegaCD_MiSTer#19]
The ram that is non functioning: 64MB SDRAM XS v1.1 (C)2017  Sorgelig

Symptoms are: 

- the core resetting repeatedly
- no animating bios screen
- no games load

I tried some various bios files and it didn't fix it. I switched back to 32MB SDRAM module and the core started working fine.

**Comment by sorgelig** [comment]
64MB modules are unreliable. I suggest to use either 32MB or 128MB.

**Comment by Aquas77** [comment]
I confirmed the 64MB module was my issue when I swapped back to 32MB and it functioned correctly.
