### ISSUE TITLE
Snatcher - Yellow Pixel glitch. 

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/MegaCD_MiSTer#2]
These glitches appear once you enter the main hall of the Junker Headquarters.  

Tested with both USA Model 1 V1.10 Bios and Region Free Bios. 

![IMG_7973](https://user-images.githubusercontent.com/36483667/70195654-e850c100-16cb-11ea-9b31-2261756286c9.jpg)

**Comment by mholzinger** [comment]
Confirming the same issue, sharing my Mister binary version, RBF hash and BIOS hash.

Sprite output in MegaCD core while playing Snatcher reveals line output in character dialogue screens.

MiSTer Binary version: 191205

MegaCD build: MegaCD_20191205.rbf
md5sum: 16420d06e8b3771e9217b2e9f7890f0e

SegaCD Bios used: Sega CD (U) - M2 V2.21.bin
SegaCD Bios md5sum: baca1df271d7c11fe50087c0358f4eb5

**Comment by JayBee-git** [comment]
I have the same issue too, same mister and binary as mholzinger.
I use a US regionfree patched bios 2.0. I also tried other bioses, they all have the same glitch.

**Comment by SegaSnatcher** [comment]
Using a test build with recent commits it seems this issue has been fixed, but will wait until a new official release is uploaded before closing this issue. 

Good work!!!

**Comment by SegaSnatcher** [comment]
I can confirm this is fixed in new official release.   

Happy Snatching guys.
