### ISSUE TITLE
Lunar the silver star- popping audio

### ISSUE THREAD

**Issue by masterninjah** [MiSTer-devel/MegaCD_MiSTer#22]
a lot of the music tracks have a small pop in the audio every couple of seconds.  it should be pretty easy to find, just start a game and run straight to the overworld.  the videos i could find didn't have this problem 
i'm using vsync2 and hdmi

**Comment by masterninjah** [comment]
this can also be heard just by listening to the tracks from the cd player.  track 9 it's really noticeable.
i forgot to say i'm using the us rom.

**Comment by JoshClose** [comment]
I'm experiencing this also. I'm using the `Lunar - The Silver Star (USA) (RE).chd` Redump ROM.

**Comment by paulb-nl** [comment]
Should be fixed with release 20230716
