### ISSUE TITLE
MegaCD CPU possibly running too slow.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/MegaCD_MiSTer#24]
NeoDev recently ran a CPU test comparing a Pal Mega CD and the MiSTer core at 50Hz and it appears the MiSTer MCD core is running a bit slower. 

Here is the results from a real Mega CD.

![IMG_20191211_200235](https://user-images.githubusercontent.com/36483667/73649015-77cf0d80-4644-11ea-868f-dbbef5765483.jpg)

Here is the results from the MiSTer core.

![IMG_20191211_200631](https://user-images.githubusercontent.com/36483667/73649084-9df4ad80-4644-11ea-96ff-c5e000210996.jpg)

Here is where you can find the test rom.

http://gendev.spritesmind.net/forum/viewtopic.php?f=8&t=2981&p=34888

**Comment by sorgelig** [comment]
i've saw that thread - there was so many versions of this test with different results. Hard to trust this test. Is there a game affected?

**Comment by SegaSnatcher** [comment]
Yes, many people believe this is the reason why Sonic CD has more slow down than real hardware. 

Granted Sonic CD has some slow down on real hardware, but many people are pretty convinced that it happens even more on the Mega CD core, and those CPU tests kinda gives weight to this assumption.

**Comment by SegaSnatcher** [comment]
Somone I talked to believes the CPU slowdown is caused by the fact that the two CPUs have to go through the single SDRAM board for access.

**Comment by sirblew** [comment]
> Someone I talked to believes the CPU slowdown is caused by the fact that the two CPUs have to go through the single SDRAM board for access.

Does using the DDR memory option help? You can do this in the Genesis/Megadrive core but I'm not sure about MegaCD.

**Comment by SegaSnatcher** [comment]
> > Someone I talked to believes the CPU slowdown is caused by the fact that the two CPUs have to go through the single SDRAM board for access.
> 
> Does using the DDR memory option help? You can do this in the Genesis/Megadrive core but I'm not sure about MegaCD.

Pretty sure MegaCD core requires ram board.

**Comment by sorgelig** [comment]
1) CD games don't use ROM(Cartridge) besides the BIOS.
2) The test rom is not really correct in CPU speed measure.
3) Recent source already has changes which "fixes" this buggy test rom.

**Comment by SegaSnatcher** [comment]
> 1. CD games don't use ROM(Cartridge) besides the BIOS.
> 2. The test rom is not really correct in CPU speed measure.
> 3. Recent source already has changes which "fixes" this buggy test rom.

Which recent source?  Do you mean a commit?

**Comment by sorgelig** [comment]
yes, there was commits since latest release.

**Comment by SegaSnatcher** [comment]
Looks like its testing correctly now.
