### ISSUE TITLE
Earthworm Jim Special Edition - Andy Asteroid Bonus Levels cause crash

### ISSUE THREAD

**Issue by neowocky** [MiSTer-devel/MegaCD_MiSTer#29]
In between stages is an Andy Asteroid bonus level. These levels cause the core to reset or just a black screen. I used the level select codes to bounce around, and it appears to be every asteroid level, not just the one after stage one that causes an issue. 

Using US version.

**Comment by SegaSnatcher** [comment]
Which release are you on?

**Comment by neowocky** [comment]
Version 20.01.01

**Comment by neowocky** [comment]
A bad rip of the game was causing the issue.
