### ISSUE TITLE
Flashback: Quest for Identity -  Freezes during intro FMV.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/MegaCD_MiSTer#30]
During the intro FMV the video freezes when the ship gets destroyed.  

Using latest release.  USA Bin/Cue, NA Sega CD Model 1 Bios.

If you press start before the freezing part occurs you can get into the game.

**Comment by bootsector** [comment]
This issue has been introduced in the latest release. Intro works fine on all previous ones.

**Comment by SegaSnatcher** [comment]
This was fixed in new release.
