### ISSUE TITLE
Stuttering Audio on FMVs (Sewer Shark and other games) after last release

### ISSUE THREAD

**Issue by Godlance** [MiSTer-devel/MegaCD_MiSTer#33]
Using the last released binary, every game seems more or less affected by choppy audio with a lot of stutter. 

Going back to the 03.25.2020 relase fix all the issues.

**Comment by IndoJimbo** [comment]
This same problem has cropped up for krikkz Mega ED. Thanks to tigheklory on twitter, it is found that you need to use the sewer shark dump from the pack in game that came with the Sega CD 2.0. The dump is labeled "not for resale". I tried it out and it works flawlessly. 

I'm not a developer, but I'm guessing that there is a difference in cd rom read speeds between the original sega cd and sega cd 2.0.

**Comment by RevQuixo** [comment]
> I'm not a developer, but I'm guessing that there is a difference in cd rom read speeds between the original sega cd and sega cd 2.0.

It has nothing to do with the Sega CD1 or 2.  It is more likely programming changes.  I tried the Not for Resale disc (an original) on my Model 1 and it did not present the skipping either.

**Comment by IndoJimbo** [comment]
Yeah I don't know about that. I'll let Sorg320 make the call. I gave my findings.

**Comment by Godlance** [comment]
It seems that with the last version of the core (20.06.20) the issue is gone for good, so I'm closing it.

Thank you!
