### ISSUE TITLE
Core reset on Scandoubler FX option change

### ISSUE THREAD

**Issue by bropesda** [MiSTer-devel/MegaCD_MiSTer#4]
Changing the Scandoubler FX option reboots the MiSTer. Using US bios 1.10.

**Comment by bropesda** [comment]
Using US bios 1.10

**Comment by sorgelig** [comment]
I can't confirm it.

**Comment by bropesda** [comment]
Strange. MD5 of the BIOS is 2EFD74E3232FF260E371B99F84024F7F.

**Comment by sorgelig** [comment]
Scandoubler option has no connection to BIOS at all.

**Comment by sorgelig** [comment]
make sure you've updated MiSTer binary to latest version.

**Comment by bropesda** [comment]
Yes everything is up to date. I can reproduce it at will. Video here https://youtu.be/a8ZHFi-Nw34

**Comment by bropesda** [comment]
Issue gone after fresh sd card creation.
