### ISSUE TITLE
Pier Solar - Enhanced CD Soundtrack

### ISSUE THREAD

**Issue by Hewhoisred** [MiSTer-devel/MegaCD_MiSTer#40]
Thanks for the new support for this.

There is a problem though.  Any time the game soft resets/reboots, it will hang (screen isn't frozen) when it gets to the watermelon splash screen.  You can see this happen, just select "about" from the main menu, or "exit" from the game, and after it resets, you'll see it hang with a very rapidly flashing disk activity LED.

Here's video of the crash:
https://youtu.be/so4zcgPWLv8

I tested with several bios versions, and all will crash the game.

**Comment by Hewhoisred** [comment]
Further info:
"neodevToday at 11:22 AM
Every time poer solar loops to the watermelon screen, it reloads the bios and resets the megacd sub-cpu"

It may have something to do with incorrect bios detection code according to Neodev.

**Comment by sorgelig** [comment]
it will be fixed in next release.
It doesn't prevent game play.
