### ISSUE TITLE
BIOS switching is broken

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/MegaCD_MiSTer#42]
In the latest release of the core (2020-06-02), BIOS switching is no longer working for me. 

I have the core set to boot with the US 2.0 region-free bios, and when switching to any other bios and then loading a game, it will revert to the bootrom bios instead of the one that was just switched to.

Discovered this while testing the Dark Wizard freezing issue further. This freezing may be related to bios issues, as it will sometimes dump the game to the bios screen when the freezing occurs.

**Comment by sorgelig** [comment]
Every disk load also reloads the BIOS.
Actually i'm planning to remove manual BIOS load as it's not so compatible with new way to load the BIOS.
just place cd_bios.rom inside the game's folder if specific game requires a specific BIOS.

**Comment by c0d3h4x0r** [comment]
So how is this supposed to work for multi-disc games that only boot off the first disc, such as Ground Zero Texas?  How do I insert disc 2 without reseting the core?  Note that the “reset on insertion” option in the OSD appears to be ignored; the core always resets even if I’ve chosen “No”.

**Comment by sorgelig** [comment]
i forgot about it. Will fix it.

**Comment by sorgelig** [comment]
https://misterfpga.org/viewtopic.php?f=16&t=379
