### ISSUE TITLE
IO board power led flashing when using MegaCD core

### ISSUE THREAD

**Issue by bropesda** [MiSTer-devel/MegaCD_MiSTer#5]
When loading Sega Classics Arcade Collection (USA) (5-in-1) using US bios 1.10 the red power led flashes constantly after loading one of the games and waiting a few minutes. Have not noticed this in any other core before. Only happens in this game (that I know of).

**Comment by sorgelig** [comment]
If game works then you should not worry. It has some signaling of different CD states.

**Comment by bropesda** [comment]
Good to know, thanks @sorgelig
