### ISSUE TITLE
Seirei Shinseiki - Fhey Area: Doesn't boot past Sega logo

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/MegaCD_MiSTer#54]
Just freezes upon being loaded up. This is the redump matching set.

**Comment by wwark** [comment]
It worked on my side.
Did you used the redump set and the japanese bios of MegaCD ?

Thanks,

**Comment by birdybro** [comment]
Sorry, I didn't follow up on this. It works fine with testing this again, closing.
