### ISSUE TITLE
Inverted left/right audio channels 

### ISSUE THREAD

**Issue by loloC2C** [MiSTer-devel/MegaCD_MiSTer#6]
It sounds like the left and right channels are inverted for CD audio.

It can be noticed during the Snatcher intro in this capture: https://youtu.be/DOsSBdIK2yw?t=348
(when the speeder goes to the right of the screen & when the dialogue starts right after).

**Comment by loloC2C** [comment]
the core passes the 240p test suite so probably a bad iso

**Comment by loloC2C** [comment]
Issue is real according to bfbiii on SmokeMonster discord "The voices are CDDA and the Suite doesn't test that", the problem happens on MiSTer but not on OEM console with MegaSD

**Comment by bfbiii** [comment]
I can confirm this happens for me on MiSTer and not on OEM console with MegaSD. MiSTer does not reverse PCM audio or any Genesis audio, but CDDA is reversed--at least in this moment.

**Comment by SegaSnatcher** [comment]
This seems fixed in recent commit.

**Comment by loloC2C** [comment]
Fixed with latest release (MegaCD_20191218.rbf)
