### ISSUE TITLE
Feature Request: Separate audio filters for FM and CD audio.  

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/MegaCD_MiSTer#68]
It would be nice if there was an option to have the CD tracks be unfiltered and just filter the FM audio.

**Comment by sorgelig** [comment]
CDDA is not filtered

**Comment by SegaSnatcher** [comment]
Sorry, I meant the Redbook CD audio.

**Comment by sorgelig** [comment]
Whatever it's called, the audio portion of CD is not filtered in the core.
There is audio filter can be applied on top of the core audio from preset file - this is completely different option managed by framework where provides already muxed common audio - this is supposed to work this way and won't be changed for obvious reason. 
But MegaCD itself doesn't filter the CD audio.

**Comment by SegaSnatcher** [comment]
Hey Sorg,  the Mega CD's built in audio filters will filter the redbook audio if you have them turned on.  Just go to the CD player tool on MCD core and play CD audio files and you'll hear redbook audio get filtered if you enable Model 1, Model 2 or Minimal audio filters.

**Comment by sorgelig** [comment]
oh, i see.. it's really filtered. 
I will change it.

**Comment by SegaSnatcher** [comment]
Thanks Sorg, sounds great.
