### ISSUE TITLE
Redbook audio popping issue

### ISSUE THREAD

**Issue by FWAF** [MiSTer-devel/MegaCD_MiSTer#80]
While playing Ecco the Dolphin (the USA version) i was hearing some noticeable audio popping with the Redbook audio.
This issue is not only in game but also while using the BIOS cd player. Tried different BIOS versions and outputs with same result.
The popping would disappear if you would rewind the track a few seconds. Also confirmed by other users. 
Here are some examples, one with normal playback and one where the track was re-winded a few seconds back (with the popping disappearing).

**with audio popping:**
https://soundcloud.com/user-803166602/ecco-the-dolphin-usa-audio-pop/s-vNzSiLPvm5T
**re-winded track**
https://soundcloud.com/user-803166602/ecco-the-dolphin-usa-rewind/s-3e44GnKAgQJ
**youtube footage of other user**
https://youtu.be/XIpreDwUbd8?t=202

tested with latest build: MegaCD_20210225

**Comment by paulb-nl** [comment]
Should be fixed with release 20230716
